### ISSUE TITLE
Generic unavailable for method-local case class with > 22 members

### ISSUE THREAD

**Issue by tpolecat** [milessabin/shapeless#479] opened 2015-10-21 18:23 UTC
(shapeless 2.2.2)

If you define a **method-local** case class, `Generic` is available only if it has 22 elements or fewer. Here's a simple failing example. Works fine if you delete a field.

```scala
scala> import shapeless._
import shapeless._

scala> :pa
// Entering paste mode (ctrl-D to finish)

object Blah {
  def x = {
    type A = Int
    case class Y(f01: A, f02: A, f03: A, f04: A, f05: A, f06: A, f07: A, f08: A, f09: A, f10: A, 
                 f11: A, f12: A, f13: A, f14: A, f15: A, f16: A, f17: A, f18: A, f19: A, f20: A, 
                 f21: A, f22: A, f23: A)
    Generic[Y]
  }
}

// Exiting paste mode, now interpreting.

<console>:19: error: could not find implicit value for parameter gen: shapeless.Generic[Y]
           Generic[Y]
                  ^
```

I should add that I'm not blocked on this ... I discovered it by accident when trying to write a compilation test that defined a class locally.

**Comment by milessabin** [comment] 2015-10-22 07:02
There have been a ton of bugs fixed in that area since 2.2.2 ... can you reproduce that with 2.2.5 or 2.3.0-SNAPSHOT?

**Comment by tpolecat** [comment] 2015-10-22 18:01
Yes, same behavior in 2.2.5 and 2.3.0-SNAPSHOT.

**Comment by triggerNZ** [comment] 2015-11-24 02:41
As an exercise in studying `Generic`, I had a look at this. It appears that this is a scala bug. Pattern matching on method-local case classes wider than 22 fields fails to compile. I raised https://issues.scala-lang.org/browse/SI-9567 (and hopefully didn't duplicate anything). There are still possible workarounds I think.

**Comment by triggerNZ** [comment] 2015-11-24 03:58
Well that was fast. Apparently fixed in https://github.com/scala/scala/pull/4862, so assuming it gets merged, this bug will disappear in 2.11.

**Comment by milessabin** [comment] 2015-11-24 08:59
Bravo! Yes, I just saw that go past. I'll check this against 2.11.8 and 2.12.0-M4 as soon as they're available.

**Comment by guersam** [comment] 2016-03-14 11:35
Tried in 2.11.8 REPL and it works now.
```
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_74).
Type in expressions for evaluation. Or try :help.

scala> import scala.language._
import scala.language._

scala> import shapeless._
import shapeless._

scala> :pa
// Entering paste mode (ctrl-D to finish)

object Blah {
  def x = {
    type A = Int
    case class Y(f01: A, f02: A, f03: A, f04: A, f05: A, f06: A, f07: A, f08: A, f09: A, f10: A, 
                 f11: A, f12: A, f13: A, f14: A, f15: A, f16: A, f17: A, f18: A, f19: A, f20: A, 
                 f21: A, f22: A, f23: A)
    Generic[Y]
  }
}

// Exiting paste mode, now interpreting.

defined object Blah

scala> Blah.x
res0: shapeless.Generic[Y]{type Repr = shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.::[Int,shapeless.HNil]]]]]]]]]]]]]]]]]]]]]]]} forSome { type Y <: Product with Serializable{val f01: A; val f02: A; val f03: A; val f04: A; val f05: A; val f06: A; val f07: A; val f08: A; val f09: A; val f10: A; val f11: A; val f12: A; val f13: A; val f14: A; val f15: A; val f16: A; val f17: A; val f18: A; val f19: A; val f20: A; val f21: A; val f22: A; val f23: A; def co... 
```

**Comment by milessabin** [comment] 2016-03-14 20:27
@guersam thanks for checking ... closing this now :-)

**Closed by milessabin** 2016-03-14 20:27 UTC
Labels: Bug
