### ISSUE TITLE
slow performance for sealed traits with large number of case objects

### ISSUE THREAD

**Issue by cvogt** [milessabin/shapeless#620] opened 2016-07-19 16:21 UTC
As discussed here: https://gitter.im/milessabin/shapeless?at=578d59c20720fd587a91e5a4

Example here:
https://github.com/milessabin/shapeless/blob/master/examples/src/main/scala/shapeless/examples/sexp.scala#L121

**Comment by cvogt** [comment] 2016-07-19 16:21
apparently miles is working on a compiler level fix

**Comment by cvogt** [comment] 2016-07-19 17:34
seems related to https://github.com/milessabin/shapeless/issues/381

**Comment by milessabin** [comment] 2016-08-18 08:22
Yup, this is a duplicate of #381.

**Closed by milessabin** 2016-08-18 08:22 UTC
