### ISSUE TITLE
Strange behavior when using -release 8 scalac option

### ISSUE THREAD

**Issue by Jasper-M** [milessabin/shapeless#1254] opened 2022-03-25 18:02 UTC
```
scalaVersion := "2.13.8"

libraryDependencies += "com.chuusai" %% "shapeless" % "2.3.8"

scalacOptions ++= List("-release", "8")
```

```
Welcome to Scala 2.13.8 (OpenJDK 64-Bit Server VM, Java 11.0.14).
Type in expressions for evaluation. Or try :help.

scala> shapeless.LabelledGeneric[java.time.Instant]
val res0: shapeless.LabelledGeneric[java.time.Instant]{type Repr = shapeless.HNil} = shapeless.LabelledGeneric$$anon$2@6f3ac7af
```

Shapeless seems to treat `java.time.Instant` as a nullary case class now.
The culprit is probably the compiler, but filing it here too since shapeless and downstream libraries are affected.

**Comment by Jasper-M** [comment] 2022-03-25 18:06
Compiler ticket and likely cause of this issue: https://github.com/scala/bug/issues/12565

**Comment by joroKr21** [comment] 2022-03-25 18:07
wow 😮

**Comment by joroKr21** [comment] 2022-03-26 20:08
Since the bug was confirmed in Scala and already has PR I think we can close it here

**Closed by joroKr21** 2022-03-26 20:08 UTC
