### ISSUE TITLE
Compile error with Generic + ADT in a method

### ISSUE THREAD

**Issue by durban** [milessabin/shapeless#614] opened 2016-06-24 18:55 UTC
This code produces a compile error (full example: https://github.com/durban/akka-typed-examples/blob/d784a3132efbd9255437fcd709389bb5a27fe687/src/main/scala/com/example/shless/NestedGeneric.scala):

``` scala
package com.example.shless

import shapeless._

class NestedGeneric {

  def foo(): Unit = {

    sealed trait U
    object U {
      final case class C(i: Int) extends U
      final case object D extends U
    }

    Generic[U]
  }
}
```

The error is somewhat strange:

```
[trace] Stack trace suppressed: run last compile:compileIncremental for the full output.
[error] (compile:compileIncremental) scala.reflect.internal.Types$TypeError: value <none> is not a member of com.example.shless.NestedGeneric
```

If I run `last compile:compileIncremental`, I get a big stacktrace (attached). If I comment out the line `Generic[U]`, there is no error.

**Comment by durban** [comment] 2016-06-24 18:56
The big stacktrace:
[error.txt](https://github.com/milessabin/shapeless/files/332380/error.txt)

**Comment by milessabin** [comment] 2016-06-25 08:29
Reproduced ... thanks. A workaround would be to unnest the ADT.

**Comment by durban** [comment] 2016-06-25 09:35
Yeah, that's what I'm doing currently. The error also seems to go away if the ADT definition is still inside the method `foo`, but `C` and `D` are not defined inside the object `U`.

**Comment by joroKr21** [comment] 2017-09-10 15:42
This seems completely broken:
1. **In object** (compiler error)
```scala
object NestedGeneric extends App {
  import shapeless._
  
  def foo(): Unit = {
    sealed trait T
    object T {
      case object O extends T
    }

    println(Generic[T])
  }

  foo()
}
```
```scala
Error:(10, 20) Internal error: unable to find the outer accessor symbol of class anon$macro$1
    println(Generic[T])
Error:(10, 20) Internal error: unable to find the outer accessor symbol of <none>
    println(Generic[T])
```
2. **In def** (compiler error)
```scala
object NestedGeneric extends App {
  import shapeless._

  def foo(): Unit = {
    sealed trait T
    def t: T = {
      case object O extends T
      O
    }

    println(Generic[T].to(t))
  }

  foo()
}
```
```scala
Error:scala: Error: Could not find proxy for lazy val O$module: scala.runtime.LazyRef in List(lazy value O$module, method t$1, object NestedGeneric, package <empty>, package <root>) (currentOwner= method to )
```
3. **In val** (ok)
```scala
object NestedGeneric extends App {
  import shapeless._

  def foo(): Unit = {
    sealed trait T
    val t: T = {
      case object O extends T
      O
    }

    println(Generic[T].to(t)) // Inl(O)
  }

  foo()
}
```
4. **In val again** (runtime error)
```scala
object NestedGeneric extends App {
  import shapeless._

  def foo(x: Boolean): Unit = {
    sealed trait T
    val t: T = if (x) {
      case object O extends T
      O
    } else {
      case object U extends T
      U
    }

    println(Generic[T].to(t))
  }

  foo(true)
}
```
```yaml
Exception in thread "main" java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    NestedGeneric$.foo(Z)V @46: aload_3
  Reason:
    Type top (current frame, locals[3]) is not assignable to reference type
  Current Frame:
    bci: @46
    flags: { }
    locals: { 'NestedGeneric$', integer, 'java/lang/Object' }
    stack: { 'scala/Predef$', 'shapeless/Generic$', uninitialized 42, uninitialized 42 }
  Bytecode:
    0x0000000: 1b99 0013 bb00 4e59 b700 4f4e 2a2d b600
    0x0000010: 53a7 0012 bb00 4e59 b700 4f3a 042a 1904
    0x0000020: b600 574d b200 5cb2 0061 bb00 1259 2d19
    0x0000030: 04b7 0064 b600 682c b900 6e02 00b6 0072
    0x0000040: b1                                     
  Stackmap Table:
    same_frame(@20)
    same_locals_1_stack_item_frame(@35,Object[#4])

	at NestedGeneric.main(NestedGeneric.scala)
```
What I would expect:
1. works
2. to 4. no implicit `Generic` found

**Comment by milessabin** [comment] 2017-09-11 11:02
@joroKr21 thanks for those examples. I'm pretty sure these are all the consequences of scalac bugs relating to companion objects of nested types. There might or might not be a fix for them in shapeless. In any case I'll see if I can identify the scalac issue which is prompting them.

**Comment by joroKr21** [comment] 2017-09-11 12:41
@milessabin I think there is definitely a  bug in `GenericMacros`, because manually expanding a `Generic` implementation in 1. works and in 2. to 4. we cannot write such an implementation because we cannot bring the subtypes into scope.

The problem is most probably in [`ctorsOfAux`](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/generic.scala#L382-L459). In 1. it should give us the type `T.O` but it gives us `NestedGeneric.T.O` which doesn't exist (or maybe it does after some later compiler phase, but not during the typer). In 2. to 4. it should abort because the subtypes are not accessible but it doesn't.

There might be some Scala bugs involved as well. IMO it has too lax rules regarding accessible types. In particular scalac will sometimes infer types that we cannot write explicitly:
```scala
@ Seq.canBuildFrom[Int] 
res7: CanBuildFrom[Seq.Coll, Int, Seq[Int]] = scala.collection.generic.GenTraversableFactory$$anon$1@5eb054
```

**Comment by milessabin** [comment] 2017-09-11 12:51
Ahh ... yes, right ... in (2) .. (4) the subtypes don't have a stable prefix as seen from the `Generic` materialization site, so they should be excluded.

**Comment by joroKr21** [comment] 2017-09-15 16:59
@milessabin There's an even more disturbing example that compiles and doesn't throw runtime exceptions, but doesn't behave as expected:
```scala
object NestedGeneric extends App {
  import shapeless._

  sealed trait T
  case class C(i: Int) extends T
  val t: T = {
    new T { }
    C(42)
  }

  val gen = Generic[T]
  println(gen.to(t)) // Inl(C(42))
  println(gen.to(C(42))) // Inr(Inl(C(42)))
}
```
Note that we cannot distinguish whether the anonymous class above is actually assigned to `t`. But this is assumed in the [`EnumVal` tests](https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/generic.scala#L860-L865). So it can't be fixed without changing the spec. IMHO we should drop support for anonymous subclasses of the sealed trait.

**Comment by milessabin** [comment] 2017-09-15 17:55
Nice catch!

**Closed** 2020-03-25 11:17 UTC
Labels: Bug
