### ISSUE TITLE
consider official support of scalajs

### ISSUE THREAD

**Issue by antonkulaga** [milessabin/shapeless#347] opened 2015-03-29 00:38 UTC
As ScalaJS is already production-ready and many popular libraries officially crosscompile to it, please consider crosscompilation of shapeless to scalajs. At the moment there are two scalajs forks of shapeless (one by @alexander-myltsev and one by @japgolly) , so I suggest to talk with them and if at least one of them will be ok to take care of all scala-js related shapeless issues - crossbuild to scalajs.

**Comment by milessabin** [comment] 2015-03-29 01:24
Have you seen the commentary on #100?

**Comment by antonkulaga** [comment] 2015-03-29 02:16
Yes, I have seen it but it was long time ago. ScalaJS is more stable now and building cross scala/scalajs projects is easier, many popular libraries (like scalacheck ) already officially crossbuild to scalajs.

**Comment by milessabin** [comment] 2015-03-29 09:01
The issue now, as it was then, is that Scala.js build issues are best looked after by people that work with Scala.js regularly. That's not me, at least not right now. A fork of shapeless that's maintained by someone who knows and cares about Scala.js seems completely appropriate.

I'm not opposed in principle to having Scala.js build related things in the main shapeless repo, but I don't see what value it adds for anyone ... all it would do is put me in the loop for Scala.js build publishing which I don't think I have anything to contribute to.

I'd be interested to hear @alexander-myltsev and @japgolly's opinions on this ... has the situation changed since the discussion we had on #100? Why are the two Scala.js forks of shapeless? Would there be any benefit in having a Scala.js branch in this repo instead?

**Comment by japgolly** [comment] 2015-03-29 09:51
To shed light on why there are two forks, let me quote myself in https://github.com/japgolly/scalacss/issues/23:

> I don't mind who does the forking, but this is what matters to me:
>
> 1. Fork should be on maven central. I don't want to add special resolvers.
> 2. New forks should be published immediately when a new version of Shapeless is out.
> 3. New forks should be published immediately when a new version of Scala.JS is out.

There's no other reason than the points above. I haven't changed any of Shapeless' source code.

As to be benefit of having a Scala.JS build closer to home here, the benefit would be that declaring dependencies is cross-JVM/JS projects is easier. Easier in that
1. a different artifact ID needn't be specified for both JVM/JS modules.
2. the developer needn't start googling for the artifact ID of the fork.
3. there is no confusion about which fork to use. (Although I feel I'm a little noisier than Alex, if he's republished since 2.0.0 I haven't seen it so hopefully my announcements reduce the confusion somwhat.)

The disadvantage of having a Scala.JS build maintained here would be that any Scala.JS specific problems:
1. May not be very high on @milessabin's priority list.
2. May be more effort to mitigate when code is shared. (For example, if a subset of a useful project's functionality relies on part of Java that isn't yet supported by Scala.JS, I have no qualms modifying or even deleting it from my fork to provide the currently-working subset.)

It'd be nice to have an unambiguous official Shapeless port of Scala.JS but I'd just hope that it were maintained attentively. @milessabin hasn't fallen in love with Scala.JS just yet; I'm happy to wait and maintain a fork until then.

**Comment by milessabin** [comment] 2015-03-29 10:25
I don't know about "fallen in love with", but I am extremely impressed by Scala.js, and I'd love to support it as a first-class platform.

I'd be happy to do that on a branch in this repo (similarly to the way I branch to support Scala 2.10.x) if someone can volunteer to maintain the Scala.js specifics and merge from master regularly. I'll also need idiot proof instructions on what to do about publishing (both SNAPSHOTs via Travis and RCs and final releases). Currently @khronnuz is doing some work on automating the release process for the two JVM branches, so maybe his input would be useful here too.

**Comment by benhutchison** [comment] 2015-03-29 11:25
Puts hand up for the job, If no one else wants it.

Im actively using scala js and maintain a cross build atm, https://github.com/benhutchison/prickle. I suspect most of the code diff for scala.js will be in build.sbt, not shapeless itself.

**Comment by milessabin** [comment] 2015-03-29 12:04
I think I'd like to see consensus between the people who have a strong interest in this. AFAIK @japgolly has been maintaining the most used fork ... can you work together to get a sensible branch together?

I'm happy to make whoever wants to take this on a contributor on the repo so you can merge to the branch without having me as a bottleneck.

**Comment by japgolly** [comment] 2015-03-29 21:26
That's great news. :)

I'd like to be involved in the maintenance. I should probably just let go but I'm a little paranoid that small things will be missed :P

**Comment by benhutchison** [comment] 2015-03-29 22:09
@japgolly I reckon you're the right person to maintain if you're willing.
Im happy to be in reserve.

**Comment by InTheNow** [comment] 2015-03-30 09:42
Had a chat on scalajs on testing and getting scalajs into main - here is an abridged copy:

>InTheNow  Have you/others thought about test migration? I believe you currently use junit
> 
milessabin I don't want to move from JUnit ... given the option I'd rather not have any Scala dependencies in core.
>
InTheNow  jUnit is not cross-compiled to sjs - so the tests can only be run in JVM. other test frameworks - uTest. zCheck - do
>
milessabin OK, that's a problem. I'm afraid it means that you'll have to rely on the JVM-based tests.
>
InTheNow Unless we migrated your tests for you.
>
milessabin That doesn't help. I don't want any Scala dependencies at all. I use very little of JUnit, so I'd consider a JUnit compatibility library for a Scala.js branch of shapeless. [Junit is] a Java dependency. Which means I have no issues with Scala binary compatibility.
>
InTheNow what about something like scalaz's speclite? ( but lifted from scalaz) I reckon we could implement that in shapeless in [2-3] file.  It's not a scala dependency - its one file in your library - ie your "own" test framework
>
milessabin OK, yes, that would work. How does that get along with SBT? WRT test detection, running, reporting etc.
>
InTheNow  well sbt has a lot built in already, one only has to add a few files to do the actual fingerprinting
Here's a plan:
No sjs testing == problem for sjs in main
you don't want to have scala deps
=> we/I do a POC to see what we can do
=> @milessabin gets sjs in main
>
milessabin I'm sold on @InTheNow's minimal, Scala, in-repo test framework proposal. I think that'd be a win all round. I have no great love for JUnit ... so long as it's small I'd prefer something idiomatic for Scala.
>
>InTheNow no scalacheck
>
The good news is that it looks like shapeless mainly/only uses assertEquals() that is easy to wrap to something else - even just to java assertion. Junit uses a test annotation to define a test function. If we could wrap that, we would have a nice POC
the output in sjs would be ... a bit [basic], but would be first class in JVM as it would still use pure Junit. I guess this would be a nice tradeoff
>
E.g - for each class in test, we make extend from, say, ShapelessTest. On Jvm, this does nothing. On sjs, this is a) the fingerprint marker b) has a compile time macro that generates code to call all methods annotated with "test". Plus need the 2/3 sbt test framework/runner files
So long as we don't try to wrap/port the entire Junit framework, it looks doable

**Comment by milessabin** [comment] 2015-03-30 19:11
Sounds plausible.

Does Scala.js have backends for more than one mainline Scala version? ie. 2.10.x vs. 2.11.x and going forward 2.12.x etc.?

**Comment by InTheNow** [comment] 2015-03-30 19:22
yes, every scala version - from their build file:

```
crossScalaVersions := Seq(
        "2.10.2",
        "2.10.3",
        "2.10.4",
        "2.10.5",
        "2.11.0",
        "2.11.1",
        "2.11.2",
        "2.11.4",
        "2.11.5",
        "2.11.6"
      )
```

**Comment by milessabin** [comment] 2015-03-30 20:17
Gotcha.

The shapeless build uses branches to handle Scala version differences. Currently master it 2.11.x and the scala-2.10.x branch is for ... Scala 2.10.x. So we'll need two Scala.js, one for each.

Cross builds within those branches for the minor version number bumps should be fine, with the proviso that shapeless only supports Scala >= 2.10.4.

**Comment by InTheNow** [comment] 2015-03-30 20:38
why not have the scalajs in with the jvm  - its by far the best approach.

**Comment by milessabin** [comment] 2015-03-30 20:55
I've found branches by far the best way to handle Scala version differences thus far. I view the Scala.js variants to be more of the same, so I'd want to support them in the same way. I'm not entirely ruling out an alternative, but you'll need to make a very compelling case for it.

**Comment by InTheNow** [comment] 2015-03-30 20:59
It looks like @japgolly  and @benhutchison  are OK with supporting this approach (yes?). I've forked  @japgolly build and will get a version of the tests there, so you can all have a look.

**Comment by milessabin** [comment] 2015-03-30 21:01
@japgolly's existing fork is basically a branch, just hosted in a different repo. I think branching is the right way to go.

**Comment by benhutchison** [comment] 2015-03-31 01:12
Ideally of course, we'd run tests over the generated JS build of shapeless, but I see it as a nice-to-have, not a must have. If its alot of work, Im comfortable relying on the JVM tests as a pretty good warranty of correctness. IME so far, the kind of typeful/non-reflective/portable code in Shapeless, Scalaz and the like translates easily into scala.js. If there's a bug in the JS version only, it's likely a bug in the scala.js platform.

**Comment by milessabin** [comment] 2015-03-31 05:49
Beyond the constraints outlined above I'm happy for all of you to work out the best approach among yourselves. Is there anything you need from me to move this forward?

**Comment by japgolly** [comment] 2015-03-31 06:09
All sounds good.

Branches will be the least invasive and we can always merge builds in the future if there's a desire to do so.

Regarding tests, Scala.JS has proven _extremely_ reliable, so much so, that JVM tests passing gives me more than enough confidence that the JS will work. However, the JS build has a unique problem that the JVM doesn't, and that is Scala.JS's javalib coverage. Specifically, if a part of Shapeless uses a part of Java that isn't (yet) supported by Scala.JS, it isn't readily apparent. It becomes a linking error in client libraries just like the good ole C++ days. Having test coverage (in place of a linker tool) will allow us to identify any such areas and either rewrite or remove them on the SJS side. @InTheNow if you're able to provide tests that would be awesome but as @benhutchison it's not a show-stopper IMO.

As to what else we'd need from @milessabin, I think it's just the house keys :grinning: Access to write to the repo and publish through Sonatype. Organisationally, I imagine we'd manage the branches by ourselves and check with you before we do releases. Is that in line with what you're thinking?

**Comment by milessabin** [comment] 2015-03-31 06:46
Access to the repo is fine ... I'll add you all a collaborators now.

I'd prefer to do the publishing step myself ... ideally I'd want to publish shapeless releases simultaneously for all supported platforms.

**Comment by milessabin** [comment] 2015-03-31 07:04
@japgolly, @khronnuz, @InTheNow ... for some reason I don't seem to be able to add you as collaborators at the moment ... the UI can't find your handles and isn't allowing me to hit the "Add collaborator" button. This might be a side-effect of the DDoS ... I'll keep trying.

If anyone knows of an alternative way to invite a collaborator, please let me know.

**Comment by milessabin** [comment] 2015-03-31 07:06
My mistake ... I shouldn't have prefixed your handles with an "@" ... force of habit ;-)

**Comment by japgolly** [comment] 2015-03-31 07:24
Thanks, that seems to have worked.

No problem at all re publishing. I'd like to back-publish a build for 2.1.0
so if that's ok, I'll ping you when it's ready :)

(Note: From Maven's point of view, SJS releases differ from Scala releases
in the same way that a Scala 2.11 build differs from a Scala 2.10 build:
different artifact IDs. Thus despite 2.1.0 being published already, there's
no problem publishing a SJS build at a later date.)

**Comment by milessabin** [comment] 2015-03-31 07:33
@japgolly gotcha ... from my PoV that gets along well with a "one branch per platform" policy.

**Comment by milessabin** [comment] 2015-03-31 09:07
FYI, I think for shapeless 2.2.0 I'll stop building for specific Scala 2.10.x versions ... there are now more 2.10.x variants which are compatible than aren't, and upgrading from 2.10.{0,1} to one which is shouldn't be a problem.

**Comment by milessabin** [comment] 2015-03-31 09:37
Quick sanity check. I'm adding `with Serializable` more or less everywhere to support Spark ... this isn't going to be a problem for Scala.js, is it?

**Comment by InTheNow** [comment] 2015-03-31 13:00
>adding with Serializable

Either sjs supports it or we can add a stub for it in sjs. Otherwise, we'll find another solution :)

Re the JS tests - I think _not_ having them is a blocker for a lot of folks, including me. I do undersatnd the argument of where things normally fail due to missing libs - and yep, unlikely to be an issue here. But as shapeless has a habit of pushing the compiler, the chances of finding a compiler bug is alot higher than usual  

But no issue here, I've got an easy solution: I'll add them. I'll post a small POC for both JVM and JS for one test class so you all can agree before porting all tests.

**Comment by milessabin** [comment] 2015-03-31 16:28
That's good. If you can do the PoC as a pull request against master that'd be great.

**Comment by benhutchison** [comment] 2015-03-31 22:23
On Wed, Apr 1, 2015 at 12:00 AM, Alistair Johnson <notifications@github.com>
wrote:

> But as shapeless has a habit of pushing the compiler, the chances of
> finding a compiler bug is alot higher than usual
>
>
Agree that shapeless pushes the compiler, but for the bug to show up /only
under JS/ it would have to be in the backend js codegen specifically.
Parsing/macros/typecheck/implicits are all identical between Scala.js and
Scala.jvm, and that where shapeless does its thing. Thats part of why
scala.js is so successful. At the value-level, what shapeless does is plain
and simple: call functions, pass parameters.

**Comment by japgolly** [comment] 2015-04-02 21:11
Personally, I'm on the fence wrt whether or not we should proceed before tests.
@InTheNow do you have a rough idea when you'll have a PR already?

Also @milessabin, when do you think 2.2.0 final will be ready? It'd be very nice to have its accompanying Scala.JS build be official. :)

**Comment by milessabin** [comment] 2015-04-03 08:22
I'm going to have to make an emergency RC3 because I screwed up `SingletonProductArgs`, but Ideally I'd like to go final in a week or so if there are no other showstoppers.

Nb. it's too late to include a new test framework for 2.2.0, but I would very much like to be able to make a simultaneous release for Scala/JVM and Scala/JS.

**Comment by InTheNow** [comment] 2015-04-03 08:58
cool. Re the new test fw, my comment has not come across as I intended as I knew it shouldn't go into 2.2.

What I was trying to say that even though I have something to look at, I think it is better if I keep it private for now so we/you can focus on the release. In a day or two I might push something to my GH but I don't want to create any stress around release time :)

**Comment by japgolly** [comment] 2015-04-04 04:41
Alrighty, you'll find that there are now two new branches.

##### scalajs-2.11.x :+1: 

Easy as pie (assuming pie is easy - I'm not a chef). Build is infused with Scala.JS.
Treat it as you would the Scala build, so `sbt publishLocal` etc.

I've published this locally and tested it with [ScalaCSS](https://github.com/japgolly/scalacss/) and my private, much larger Scala.JS project. All compiles, all tests pass.

##### scalajs-2.10.x :-1: 

*Not* as easy as pie (note above assumption about pies). `core` compiles fine but compiling the  `examples` module produces a compiler crash in the compiler jscode phase:

`[error] (examples/compile:compile) java.lang.AssertionError: assertion failed: Unsound substitution from List(type V) to List(type V, value unwrap, method label, method unlabel, type V)`

I'll bring this up with Seb on the SJS-side.

Regardless of how the Scala 2.10 build goes, having the 2.11 build out will be a big win.

**Comment by milessabin** [comment] 2015-04-04 08:31
Awesome! Thanks for that! When the time comes, is `published-signed` all that has to be done?

For scala-2.10.x ... is this a regression relative to shapeless 2.1.0? Also ignoring the examples, do the core tests compile and run successfully?

**Comment by ngbinh** [comment] 2015-04-04 09:28
awesome! :clap:

**Comment by japgolly** [comment] 2015-04-04 11:33
@milessabin My pleasure :) And yes, `sbt publish-signed` is all that's needed. All the normal SBT commands that work on the main Scala branch should work identically on the Scala.JS branch. (If ever that's not the case, let me know and I'll fix it.)

Regarding the tests -- I want to clarify a point and make sure there's no misunderstanding here -- they compile but they *cannot be run* because JUnit isn't available in JS. When I say *"all tests pass"* in my previous comment, I'm referring to tests in other (mentioned) Scala.JS projects that *depend* on Shapeless. When we get the new test framework (discussed in other comments above) into Shapeless, then we'll be able to run Shapeless' tests in JS. I *think* we're all clear on that but I want to clarify a potential ambiguity there.

About Scala 2.10, I..... don't know if it's a regression since 2.1.0. I was actually under the impression that Scala 2.10 support was new with upcoming 2.2.0. Realising my error, I've just tried 2.1.0 on 2.10 with SJS and couldn't (quickly) get around some odd dependency/build problem. Let me spend some time on it before I answer.
The tests in core also crash the compiler. We've an issue raised: https://github.com/scala-js/scala-js/issues/1581

**Comment by InTheNow** [comment] 2015-04-07 09:48
I've pushed the first cut of the tests to https://github.com/InTheNow/shapeless. The tests use macro paradise to give macro annotations for juint's `@Test`, neither of which I would like to keep. Rather, see `core/src/test/scala/shapeless/hlistSpecLite.scala` that has the SpecLite format, that is also what the macro expands to (sort of). The duplicate test also explaind the extra tests below and the two extra failures.

```
[info] ! :testPartialOrdering failed: Expected (Some(-23)) to equal (Some(-1))
[info] ! :testRotateLeft failed: Expected (i: 1, s: foo, d: 2.0) to equal (i: 1, s: foo, d: 2)
[info] ! :testRotateRight failed: Expected (i: 1, s: foo, d: 2.0) to equal (i: 1, s: foo, d: 2)
[info] ! :testHList failed: Expected (false) to equal (true)
[info] ! :testEither failed: Expected (false) to equal (true)
[info] ! :testTuples failed: Expected (false) to equal (true)
[info] ! :testMkString failed: Expected (<1;foo;2.0>) to equal (<1;foo;2>)
[info] ! :testRejectBogus failed: An undefined behavior was detected: undefined is not an instance of shapeless.TypeOperatorTests$Foo
[info] ! :testMkString failed: Expected (⸨1, foo, 2.0⸩) to equal (⸨1, foo, 2⸩)
[info] ! :testUpdate failed: Expected (1 :: true :: foo :: 2.0 :: HNil) to equal (1 :: true :: foo :: 2 :: HNil)
[info] ! HListTests:testUpdate failed: Expected (1 :: true :: foo :: 2.0 :: HNil) to equal (1 :: true :: foo :: 2 :: HNil)
[info] ! HListTests:testMkString failed: Expected (⸨1, foo, 2.0⸩) to equal (⸨1, foo, 2⸩)
[info] Failed: Total 442, Failed 0, Errors 12, Passed 430
[error] (shapeless-core/test:test) sbt.TestsFailedException: Tests unsuccessful

```

Also, there are linking errors when using `set scalaJSStage in Global := FastOptStage`
In particular, all the calls to map in testInlinePoly, testLiftImported, testLiftPath, testLiftLocal and testLiftEnclosing in PolyTests cause the linker to crash. Search for `Todo:` to find the relevant code.

**Comment by japgolly** [comment] 2015-04-08 07:06
I had a chat with @InTheNow. Summary of the situation:
* New suggested, embedded test framework is called SpecLite. ([Code here](https://github.com/InTheNow/shapeless/tree/shapeless-2.1.0-js/core/src/test/scala/shapeless/test)).
* There is a macro to make the current tests work almost as-is ([sample](https://github.com/InTheNow/shapeless/blob/shapeless-2.1.0-js/core/src/test/scala/shapeless/hlist.scala)). Alternatively, tests can be rewritten to match the embedded test framework's expected format ([sample](https://github.com/InTheNow/shapeless/blob/shapeless-2.1.0-js/core/src/test/scala/shapeless/hlistSpecLite.scala)).
* The results of running the tests in JS are 10 failures and a number of linking errors.

Where do we go from here? I suggest the following:
* Create a separate issue for @InTheNow's test change proposal. Immediately verify in new ticket if @milessabin is ok with the direction its heading in. Busy, compartmentalising me mostly removes self from issue until an approving @milessabin merges something into `master`.
* As the Scala-2.10-JS build fails due to what seems like a Scala.JS bug, ignore 2.10 for now. Maybe raise an issue here if preferred.
* Consider the Scala-2.11-JS build acceptable and publish alongside Shapeless 2.2.0.
* Later, investigate the JS test failures. If they are legitimate failures, fix and republish.
* Close this ticket.

Why publish a 2.11 build if there seem to the test failures?
* Regardless of their potential presence, libraries and people are already building and using JS-builds of Shapeless to the point that there is confusion over which fork to use.
* The vast majority of, if not all SJS users acknowledge that SJS is a work-in-progress and understand there may still be hiccups, there is no warranty.
* All know that Shapeless on Scala/JVM is solid and passes its tests.

**Comment by InTheNow** [comment] 2015-04-08 08:20
quick update on failing tests in JS - I've gone through all of them and nothing serious at all.

**Comment by InTheNow** [comment] 2015-04-08 18:44
Linker crashes put in mini-project and raised with scalajs 

@milessabin What are your thoughts on moving this fwd? Would it be useful for an offline chat (gitter, skpe, etc), as I did with @japgolly?

**Comment by milessabin** [comment] 2015-04-09 10:39
I'm slightly suspicious of the use of the macro annotation in the new tests. Could you take one of the ones that fail tests and run its JUnit original as a main class?

**Comment by milessabin** [comment] 2015-04-09 10:40
I'm happy to publish a 2.11 Scala.js build of 2.2.0-RC4 if you think that would move things along.

**Comment by InTheNow** [comment] 2015-04-09 11:15
>I'm slightly suspicious of the use of the macro annotation in the new tests. Could you take one of the ones that fail tests and run its JUnit original as a main class?

Sort of why I wanted a quick chat to fully explain what is going, but the quick answer now is:

- The tests pass in JVM
- Junit cannot cross-compile to sjs, and probably never will
- the macro annotation is a _temporary_ solution to get the tests running without having to refactor all of the tests. As an example - see [hlist](https://github.com/InTheNow/shapeless/blob/shapeless-2.1.0-js/core/src/test/scala/shapeless/hlist.scala) vs [new hlist](https://github.com/InTheNow/shapeless/blob/shapeless-2.1.0-js/core/src/test/scala/shapeless/hlistSpecLite.scala). The only reason that i took the macro approach is that I did not want to change *every* test file before the release in case they change. But as we are at RC4, maybe I should just do it? That way the macro annotations go and what-you-see-is-what(I propose)-you-get. And the PR will be against the JS branch so will not effect master but can be cherry git merged later if approved

Also, I have gone through each failing test and know why they have failed and fixed accordingly ( mostly down to differing semantics in JS/ JVM.

I can prepare a proper branch for this and merge into the JS branch for a release of a 2.11 Scala.js build of 2.2.0-RC4.

**Comment by milessabin** [comment] 2015-04-09 11:32
If there's a semantic difference between JS/JVM that causes some of the tests to fail I'd be very keen to know the details.

Can we arrange another chat with @japgolly?

**Comment by InTheNow** [comment] 2015-04-09 11:34
Can do, but @japgolly is in Sydney time zone.

**Comment by InTheNow** [comment] 2015-04-09 16:22
Please see @sjrd 's rapid investigation on the linker (actually IR) issue https://github.com/scala-js/scala-js/issues/1585

**Comment by InTheNow** [comment] 2015-04-13 13:47
As this issue is about "considering" official scalajs support and that there are now other issues about the actual "implementation", I guess this issue can now be closed.

@antonkulaga Hi Anton, are you happy to close this?

**Closed** 2015-05-17 19:15 UTC
Labels: Blocked/needs help, Build, Feature, In progress, Scala/JS
